# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/akzi/xenonframe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/akzi/xenonframe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/akzi/xenonframe/CMakeFiles /home/akzi/xenonframe/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/akzi/xenonframe/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xnet_client

# Build rule for target.
xnet_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xnet_client
.PHONY : xnet_client

# fast build rule for target.
xnet_client/fast:
	$(MAKE) -f CMakeFiles/xnet_client.dir/build.make CMakeFiles/xnet_client.dir/build
.PHONY : xnet_client/fast

#=============================================================================
# Target rules for targets named xnet_server

# Build rule for target.
xnet_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xnet_server
.PHONY : xnet_server

# fast build rule for target.
xnet_server/fast:
	$(MAKE) -f CMakeFiles/xnet_server.dir/build.make CMakeFiles/xnet_server.dir/build
.PHONY : xnet_server/fast

#=============================================================================
# Target rules for targets named threadpool

# Build rule for target.
threadpool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 threadpool
.PHONY : threadpool

# fast build rule for target.
threadpool/fast:
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/build
.PHONY : threadpool/fast

examples/threadpool/threadpool_test.o: examples/threadpool/threadpool_test.cpp.o

.PHONY : examples/threadpool/threadpool_test.o

# target to build an object file
examples/threadpool/threadpool_test.cpp.o:
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/examples/threadpool/threadpool_test.cpp.o
.PHONY : examples/threadpool/threadpool_test.cpp.o

examples/threadpool/threadpool_test.i: examples/threadpool/threadpool_test.cpp.i

.PHONY : examples/threadpool/threadpool_test.i

# target to preprocess a source file
examples/threadpool/threadpool_test.cpp.i:
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/examples/threadpool/threadpool_test.cpp.i
.PHONY : examples/threadpool/threadpool_test.cpp.i

examples/threadpool/threadpool_test.s: examples/threadpool/threadpool_test.cpp.s

.PHONY : examples/threadpool/threadpool_test.s

# target to generate assembly for a file
examples/threadpool/threadpool_test.cpp.s:
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/examples/threadpool/threadpool_test.cpp.s
.PHONY : examples/threadpool/threadpool_test.cpp.s

examples/xnet/client/client.o: examples/xnet/client/client.cpp.o

.PHONY : examples/xnet/client/client.o

# target to build an object file
examples/xnet/client/client.cpp.o:
	$(MAKE) -f CMakeFiles/xnet_client.dir/build.make CMakeFiles/xnet_client.dir/examples/xnet/client/client.cpp.o
.PHONY : examples/xnet/client/client.cpp.o

examples/xnet/client/client.i: examples/xnet/client/client.cpp.i

.PHONY : examples/xnet/client/client.i

# target to preprocess a source file
examples/xnet/client/client.cpp.i:
	$(MAKE) -f CMakeFiles/xnet_client.dir/build.make CMakeFiles/xnet_client.dir/examples/xnet/client/client.cpp.i
.PHONY : examples/xnet/client/client.cpp.i

examples/xnet/client/client.s: examples/xnet/client/client.cpp.s

.PHONY : examples/xnet/client/client.s

# target to generate assembly for a file
examples/xnet/client/client.cpp.s:
	$(MAKE) -f CMakeFiles/xnet_client.dir/build.make CMakeFiles/xnet_client.dir/examples/xnet/client/client.cpp.s
.PHONY : examples/xnet/client/client.cpp.s

examples/xnet/server/server.o: examples/xnet/server/server.cpp.o

.PHONY : examples/xnet/server/server.o

# target to build an object file
examples/xnet/server/server.cpp.o:
	$(MAKE) -f CMakeFiles/xnet_server.dir/build.make CMakeFiles/xnet_server.dir/examples/xnet/server/server.cpp.o
.PHONY : examples/xnet/server/server.cpp.o

examples/xnet/server/server.i: examples/xnet/server/server.cpp.i

.PHONY : examples/xnet/server/server.i

# target to preprocess a source file
examples/xnet/server/server.cpp.i:
	$(MAKE) -f CMakeFiles/xnet_server.dir/build.make CMakeFiles/xnet_server.dir/examples/xnet/server/server.cpp.i
.PHONY : examples/xnet/server/server.cpp.i

examples/xnet/server/server.s: examples/xnet/server/server.cpp.s

.PHONY : examples/xnet/server/server.s

# target to generate assembly for a file
examples/xnet/server/server.cpp.s:
	$(MAKE) -f CMakeFiles/xnet_server.dir/build.make CMakeFiles/xnet_server.dir/examples/xnet/server/server.cpp.s
.PHONY : examples/xnet/server/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... xnet_client"
	@echo "... xnet_server"
	@echo "... edit_cache"
	@echo "... threadpool"
	@echo "... examples/threadpool/threadpool_test.o"
	@echo "... examples/threadpool/threadpool_test.i"
	@echo "... examples/threadpool/threadpool_test.s"
	@echo "... examples/xnet/client/client.o"
	@echo "... examples/xnet/client/client.i"
	@echo "... examples/xnet/client/client.s"
	@echo "... examples/xnet/server/server.o"
	@echo "... examples/xnet/server/server.i"
	@echo "... examples/xnet/server/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

